spring.application.name=ticket-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/ticket_management_db
spring.datasource.username=root
spring.datasource.password=GOPALTIROLE@111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=gopu
spring.security.user.password=Gopal@123
spring.security.user.roles=ADMIN